### PR TITLE
Fix retry logic for status

### PR DESCRIPTION
**Pull request by emontnemery**
I think I broke the status retry logic when messing with TuyaClient, this should fix it.

Edit: It was broken by 96340767a71df86ebb783c65c05b71c6b798a840

### CODE REVIEW

**Comment by TradeFace** [comment]
Ah in my quest to get uniform returns :) Okay, within the module that isn't the biggest problem. Public function returns should be uniform.

**Comment by emontnemery** [comment]
I think returning `None` is mostly OK 👍

**Comment by TradeFace** [comment]
Slippery slope ;) May my "correction" be evidence of that.

**Comment by jkerdreux-imt** [comment]
I think we should remove this retry anyways.

You can have a retry in two cases :

1) network issues, timeout etc, but in most case you will receive a 
exception too. ResetError...

2) By devices that reports buggy status 'invalid json ...'. If the 
device answer that so switch to another trick to get the status. (which 
is partial most device only reports 2 or 3 dps).

In this two cases, the developer can fix that by his own with exception 
handling, retry etc etc.
Most lamps I own for example have the buggy 'invalid json' stuff. So 
querying their status, always use a retry which sound stupid. I think we 
can remove that retry everywhere, raise a exception for 'invalid json' 
asking the developer to use the status trick.

**Comment by TradeFace** [comment]
It is a solution for now. In a general sense I agree this logic shouldn't be in an API. Perhaps we can make it a bit better to register a fall back to trickery in the device dict. In subsequent calls we can by pass the first status call.

**Comment by emontnemery** [comment]
I think it's reasonable that `status()` sends a status request which the device understands and that it hides quirks of the device from the user.
We could save in the `device` dict if the alternative `status` request should be sent once `unvalid json` has been received once?

**Pull request merged**
