### PR TITLE
Improve message parsing

### PR DESCRIPTION
**Pull request by emontnemery**
Improve message parsing, this is one step towards actually checking that the reply we get from a `status` or `set_state` is valid (should check sequence number, return code and command).

### CODE REVIEW

**Comment by TradeFace** [comment]
Thanks for the PR. Could you target it at the development branch?

**Comment by emontnemery** [comment]
Sure, fixed now.

**Comment by emontnemery** [comment]
By the way, let me know if you prefer several small PR like this one or one big is better.

**Comment by TradeFace** [comment]
Do what works best for you. I might not be able merge as fast every time though

**Pull request merged**
