### PR TITLE
Don't wait for status after sending CONTROL

### PR DESCRIPTION
**Pull request by emontnemery**
Don't wait for status after sending CONTROL
Also, remove `TuyaClient.connection` and use `self.device['tuyaface']['connection']`

### CODE REVIEW

**Comment by TradeFace** [comment]
I'll do some testing later on. See if we can release 1.2.0 as is.

**Comment by jkerdreux-imt** [comment]
This commit killed all my code :(
Due to set_status() returning a bool instead of the value.. 
I used a  single function that parse status() and set_status() results.

**Comment by TradeFace** [comment]
:/ hmm, that is not good. That didn't come up in my testing, since tuyamqtt isn't using those functions anymore. We should have a test script that at least tests the public interface.

**Comment by emontnemery** [comment]
@jkerdreux-imt the problem was that the previous code was not reliable, the status reply returned to the caller was not guaranteed to be a result of the `CONTROL` command.

I think it makes sense that `set_status()` sends a `CONTROL` message and reports back if that was succesful or not?

Maybe a new function could be added to do what TuyaClient does to read messages from the socket:
```py
data = self.device['tuyaface']['connection'].recv(4096)
    #logger.debug("(%s) read from socket '%s' (%s)", self.device["ip"], ''.join(format(x, '02x') for x in data), len(data))
    if data:
        for reply in _process_raw_reply(self.device, data):
            if self.on_status and reply["cmd"] == tf.STATUS and reply["data"]:
                json_reply = json.loads(reply["data"])
                self.on_status(json_reply)
```

**Comment by TradeFace** [comment]
> I think it makes sense that set_status() sends a CONTROL message and only reports back if that action was accepted or not?

I agree

What if we push the last know status in the device dict? That is easy on the implementation end

**Comment by jkerdreux-imt** [comment]
I have in example a function that transform a given white temperature to 
dps :

https://redmine.telecom-bretagne.eu/projects/xaal/repository/entry/code/Python/branches/0.7/devices/protocols/Tuya/xaal/tuya/devices.py#L330

As you can imagine some temperature aren't doable. For example 2000°K 
mapped in 25-255, can return in a real 1990°K. So I compute the dps, 
send it to device, and as I already have a parser for this in 
on_status(), everything is fine. Somebody ask for 2000°K and receive a 
notification that the real temperature is now 1990°K.

I can fix that, but this looked nice and easy to understand.

**Comment by jkerdreux-imt** [comment]
@emontnemery 
I will try implement the ping/pong in my implementation too. Some stuff are missing in the __init__.py right now to do that. 
First is the ping/pong stuff itself (only present in TuyaClient I think). And as you mention the connexion recv and process_raw. I can copy / paste your code from TuyaClient but I think this parts should be in the module itself.

Bye

**Comment by emontnemery** [comment]
@jkerdreux-imt It makes sense. I'll try to refactor TuyaClient a bit the next few days and move for example ping-pong and polling socket for status updates to __init__.py instead.

**Pull request merged**
