### PR TITLE
Move sequence number to device dict

### PR DESCRIPTION
**Pull request by emontnemery**

### CODE REVIEW

**Comment by TradeFace** [comment]
Looks great! Can the connection go in there as well as @jkerdreux-imt suggested?

**Comment by jkerdreux-imt** [comment]
I'm trying to keep my repo up-to-date and read the modification. but I 
missed something.
what is the 'seq' for ? I mean, I can't find where this is used. I know 
still sound stupid..

Bye.

**Comment by TradeFace** [comment]
seq is the sequence number of the request. In the earlier implementation I had it set to zero. In that scenario it wasn't as important because the connection was reset anyway. For tuyaclient which keeps the connection open for a longer period, and make multiple calls you might want to check for consistency / sanity between query and reply.

**Comment by jkerdreux-imt** [comment]
I know that, but this is not used here right ?

**Comment by TradeFace** [comment]
Nope no consistency / sanity checks on this side. (And as far as I can tell neither on the other). But it's good to have, maybe in the future it might come in handy.

**Pull request merged**
